### PR TITLE
Make Futures Send By Default, Allow For Opting Out

### LINKED ISSUE #1: Function Not Send?
Hey there, I wanted to use this in my project, but I'm getting an error that I don't get when manually adjusting the function for recursion:

```

error[E0277]: `(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)` cannot be sent between threads safely
  --> src/subsystems/crawler.rs:64:50
   |
64 |                     let aid = ctx.system.spawn().with(
   |                                                  ^^^^ `(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>`
   = note: required because it appears within the type `std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>>`
   = note: required because of the requirements on the impl of `axiom::actors::Processor<subsystems::crawler::IndexCrawler<P>, std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>>>` for `fn(subsystems::crawler::IndexCrawler<P>, axiom::actors::Context, axiom::message::Message) -> std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>> {subsystems::crawler::IndexCrawler::<P>::index_crawler}`
```

I noticed a TODO in the code about a `Send` option that is missing, is that related? Would it be simple enough to explain what must happen so I could make a PR?

### PR DESCRIPTION
**Pull request by zicklag**
Resolves #1 

I also removed the note about limitations around lifetimes in the README, because it looks like you fixed that, and did some slight reformatting of the README. Tell me if there is anything you don't like and want changed back.

### CODE REVIEW

File: src/parse.rs [hunk 1]
```diff
@@ -16,3 +16,38 @@ impl Parse for AsyncItem {
         Ok(AsyncItem(item))
     }
 }
+
+#[derive(Default)]
```
Comment (dcchut) [inline src/parse.rs]: Instead of deriving default here, maybe give an explicit impl where send_bound is true (given that that is the default behaviour)

File: src/parse.rs [hunk 2]
```diff
@@ -16,3 +16,38 @@ impl Parse for AsyncItem {
...
+            }
+        } else if input.is_empty() {
+            args.send_bound = true;
+        } else {
+            return Err(lookahead.error());
+        }
+
+        Ok(args)
+    }
+}
```
Comment (dcchut) [inline src/parse.rs]: I think this could be simplified a bit using [custom keywords](https://docs.rs/syn/1.0.17/syn/macro.custom_keyword.html) - I haven't checked if this works, but something like:

```suggestion
mod kw {
    syn::custom_keyword!(Send);
}

impl Parse for RecursionArgs {
    fn parse(input: ParseStream) -> Result<Self> {
        if input.peek(Token![?]) {
            input.parse::<Token![?]>()?;
            input.parse::<kw::Send>()?;
            Ok(Self { send_bound: false })
        } else {
            Ok(Self::default())
        }
    }
}
```

Comment (zicklag) [reply src/parse.rs]: Custom keywords are perfect! Fixed.

File: src/parse.rs (hunk 1 above)
Comment (zicklag) [reply src/parse.rs]: Good point. Fixed.

**Comment by zicklag** [comment]
:tada: Thanks for this crate. I wanted to make exactly this when I found you already had. :) Glad I could help!
